### ISSUE TITLE
Exercise ListsAndRecursion-5 filter - list is returned in reverse order

### ISSUE THREAD

**Issue by JCMais** [pcewing/programming-elixir-exercises#1]
the filter method is returning the list on inverse order.

For instance
```elixir
MyEnum.filter([1, 2, 3], fn x -> x >= 2 end)
```
returns
```elixir
[3, 2]
```

instead of
```elixir
[2, 3]
```

This occurs because of the following code:
https://github.com/pcewing/programming-elixir-exercises/blob/85379db4b880a06a9fe227d1e72b60f7e263951f/ch10/ListsAndRecursion-5/my_enum.exs#L30-L31

To fix that you can have the filter like the following
```elixir
  defp do_filter([h | t], condition) do
    case condition.(h) do
      true -> [h | do_filter(t, condition)
      false -> do_filter(t, condition)
    end
  end
```

doing it that way it should return the list using the initial order and also removes the need for the accumulator.

**Comment by pcewing** [comment]
Hey, thanks for the report and sorry for taking so long to respond. It's been
forever since I've done anything with Elixir so this actually gave me a reason
to get my workstation set up for it again. :)

Your approach is indeed correct; I made that change in [PR #2][pr2] and tested
it as follows:

```
iex> MyEnum.filter [1, 2, 3], fn x -> x >= 2 end
[2, 3]

iex> MyEnum.filter [1, 4, 0, -3, 5, 2, 3], fn x -> x >= 2 end
[4, 5, 2, 3]
```

Thanks again!

[pr2]: https://github.com/pcewing/programming-elixir-exercises/pull/2

**Comment by pcewing** [comment]
Hmm, re-opening because I just had second thoughts about this change. I think changing `do_filter(t, condition, [h | acc])` to `[h | do_filter(t, condition)]` will make it so that this no longer uses tail recursion which I'd like to avoid. I'm sure there's another way to fix the ordering without breaking tail recursion. I'll keep this issue open so I can think more about it when I have time.

**Comment by pcewing** [comment]
I just reverted the change and used an `Enum.reverse` to fix the ordering of
the resulting list instead. I ran some very rudimentary benchmarks to try and
measure the impact of the tail call optimization and there isn't much of a
difference between the two implementations either in execution time or RAM
consumption. That said, I still decided to change it back to maintain
consistency with all of my answers to other similar exercises which are written
to use TCO.
